export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const POP_NOTIFICATION = "POP_NOTIFICATION";
export const HIDE_FIRST_NOTIFICATION = "HIDE_FIRST_NOTIFICATION";