export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const PUSH_NOTIFICATION_TO_QUEUE = "PUSH_NOTIFICATION_TO_QUEUE";
export const POP_NOTIFICATION_FROM_QUEUE = "POP_NOTIFICATION_FROM_QUEUE";
export const HIDE_FIRST_NOTIFICATION = "HIDE_FIRST_NOTIFICATION";